services:
  postgres:
    image: postgres:15
    container_name: tfm_postgres
    restart: always
    environment:
      POSTGRES_USER: tfm
      POSTGRES_PASSWORD: tfm_password
      POSTGRES_DB: tfm_db
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  spc_generator:
    build: ./spc_generator
    depends_on:
      - postgres
    restart: "no"

  pgadmin:
    image: dpage/pgadmin4
    container_name: tfm_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tfm.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: